# Generated by Django 2.1.7 on 2019-03-22 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_playmusic_searchmusic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playmusic',
            name='image',
        ),
        migrations.AddField(
            model_name='playmusic',
            name='music_type',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
